/*
 * This is roughly based on the YAML documentation generator
 * in the original cobra sources. however, I wanted the documentation
 * to be organized in a slightly different way.
 *
 * You'll see why...
 */
package docs

import (
	"maps"
	"os"
	"sort"
	"strings"

	"github.com/spf13/cobra"
	"github.com/spf13/pflag"
	"golang.org/x/exp/slices"
	"gopkg.in/yaml.v3"
)

type DocOption struct {
	Name         string
	Shorthand    string `yaml:",omitempty"`
	DefaultValue string `yaml:"default_value,omitempty"`
	Usage        string `yaml:",omitempty"`
}

type DocCommand struct {
	Name             string
	Synopsis         string      `yaml:",omitempty"`
	Description      string      `yaml:",omitempty"`
	Usage            string      `yaml:",omitempty"`
	Options          []DocOption `yaml:",omitempty"`
	InheritedOptions []DocOption `yaml:"inherited_options,omitempty"`
	Example          string      `yaml:",omitempty"`
	ParentCmd        string      `yaml:"parent,omitempty"`
	SeeAlso          []string    `yaml:"see_also,omitempty"`
	Children         []string    `yaml:",omitempty"`
}

type DocRoot struct {
	RootCmd  DocCommand
	Commands map[string]DocCommand
}

func getSlug(cmd *cobra.Command) string {
	return strings.ReplaceAll(cmd.CommandPath(), " ", "-")
}

func genDocTree(cmd *cobra.Command) map[string]DocCommand {

	cmdDocs := make(map[string]DocCommand)

	cmdDocs[getSlug(cmd)] = genDocCommand(cmd)

	for _, c := range cmd.Commands() {
		if !c.IsAvailableCommand() || c.IsAdditionalHelpTopicCommand() {
			continue
		}
		// Append the child to the list
		docs := genDocTree(c)
		maps.Copy(cmdDocs, docs)
	}
	return cmdDocs
}

func genDocCommand(cmd *cobra.Command) DocCommand {
	cmd.InitDefaultHelpCmd()
	cmd.InitDefaultHelpFlag()

	mDocCommand := DocCommand{}
	mDocCommand.Name = cmd.CommandPath()

	mDocCommand.Synopsis = forceMultiLine(cmd.Short)
	mDocCommand.Description = forceMultiLine(cmd.Long)

	if cmd.Runnable() {
		mDocCommand.Usage = cmd.UseLine()
	}

	if len(cmd.Example) > 0 {
		mDocCommand.Example = cmd.Example
	}

	flags := cmd.NonInheritedFlags()
	if flags.HasFlags() {
		mDocCommand.Options = genFlagResult(flags)
	}
	flags = cmd.InheritedFlags()
	if flags.HasFlags() {
		mDocCommand.InheritedOptions = genFlagResult(flags)
	}

	if cmd.HasParent() {
		mDocCommand.ParentCmd = getSlug(cmd.Parent())
	}

	children := make([]string, 0)
	if cmd.HasAvailableSubCommands() {
		for _, child := range cmd.Commands() {
			if !child.IsAvailableCommand() ||
				child.IsAdditionalHelpTopicCommand() {
				continue
			}
			children = append(children, getSlug(child))
		}
	}

	mDocCommand.Children = children

	if hasSeeAlso(cmd) {
		result := []string{}
		if cmd.HasParent() {
			parent := cmd.Parent()
			result = append(result, getSlug(parent))
		}
		cmdChildren := cmd.Commands()
		sort.Sort(byName(cmdChildren))
		for _, child := range cmdChildren {
			slug := getSlug(child)
			// We want to be as careful as possible here...
			if !child.IsAvailableCommand() ||
				child.IsAdditionalHelpTopicCommand() ||
				slices.Contains(children, slug) {
				continue
			}
			result = append(result, slug)
		}
		mDocCommand.SeeAlso = result
	}

	return mDocCommand
}

func genFlagResult(flags *pflag.FlagSet) []DocOption {
	var result []DocOption

	flags.VisitAll(func(flag *pflag.Flag) {
		// Todo, when we mark a shorthand is deprecated, but specify an empty message.
		// The flag.ShorthandDeprecated is empty as the shorthand is deprecated.
		// Using len(flag.ShorthandDeprecated) > 0 can't handle this, others are ok.
		if !(len(flag.ShorthandDeprecated) > 0) && len(flag.Shorthand) > 0 {
			opt := DocOption{
				flag.Name,
				flag.Shorthand,
				flag.DefValue,
				forceMultiLine(flag.Usage),
			}
			result = append(result, opt)
		} else {
			opt := DocOption{
				Name:         flag.Name,
				DefaultValue: forceMultiLine(flag.DefValue),
				Usage:        forceMultiLine(flag.Usage),
			}
			result = append(result, opt)
		}
	})

	return result
}

func GenerateDocumentation(command *cobra.Command, path string) error {
	file, err := os.Create(path)
	if err != nil {
		return err
	}
	defer file.Close()

	root := genDocCommand(command.Root())

	children := make(map[string]DocCommand)

	for _, childCmd := range command.Commands() {
		maps.Copy(children, genDocTree(childCmd))
	}

	mDocRoot := DocRoot{
		RootCmd:  root,
		Commands: children,
	}

	body, err := yaml.Marshal(mDocRoot)
	if err != nil {
		return err
	}

	_, err = file.Write(body)
	if err != nil {
		return err
	}
	return nil
}

// These helper functions were lifted straight from cobra.

// Test to see if we have a reason to print See Also information in docs
// Basically this is a test for a parent command or a subcommand which is
// both not deprecated and not the autogenerated help command.
func hasSeeAlso(cmd *cobra.Command) bool {
	if cmd.HasParent() {
		return true
	}
	for _, c := range cmd.Commands() {
		if !c.IsAvailableCommand() || c.IsAdditionalHelpTopicCommand() {
			continue
		}
		return true
	}
	return false
}

// Temporary workaround for yaml lib generating incorrect yaml with long strings
// that do not contain \n.
func forceMultiLine(s string) string {
	if len(s) > 60 && !strings.Contains(s, "\n") {
		s = s + "\n"
	}
	return s
}

type byName []*cobra.Command

func (s byName) Len() int           { return len(s) }
func (s byName) Swap(i, j int)      { s[i], s[j] = s[j], s[i] }
func (s byName) Less(i, j int) bool { return s[i].Name() < s[j].Name() }
