# baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Ponzu'
theme="hugo-modernist"


[params]
  description = "A modern alternative to Tar"
  footer = "A project by [indrora](https://github.com/indrora) with ❤️ from Seattle"

[menus]
  [[menus.main]]
    pre = "Visit"
    name = 'Home'
    pageRef = '/'
    weight = 10

  [[menus.main]]
    pre = "Read the"
    name = 'Docs'
    pageRef = '/docs'
    weight = 20

  [[menus.main]]
    pre = "View on"
    name = 'GitHub'
    url = "https://github.com/indrora/ponzu"
    weight = 30

[module]
  [module.hugoVersion]
    extended = false
    min = '0.146.0'
